"""Complete Imperial Advanced Aeronautical Engineering with scoped official evidence."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; CHECKED="2026-07-15"
def bi(en,tr): return {"en":en,"tr":tr}
def source(url,title,kind,fields,en,tr): return {"url":url,"title":title,"source_type":kind,"access_status":"ok","last_checked":CHECKED,"relevant_fields":fields,"confidence":"high","notes":bi(en,tr)}
p=ROOT/"data_base"/"ingiltere.json";raw=p.read_text(encoding="utf8");d=json.loads(raw);rows=d if isinstance(d,list) else d.get("programs",d.get("universities",[]));r=next(x for x in rows if x.get("id")=="imperial-college-london")
course="https://www.imperial.ac.uk/study/courses/postgraduate-taught/advanced-aeronautical-engineering/";living="https://www.imperial.ac.uk/study/pg/fees-and-funding/living-costs/";language="https://www.imperial.ac.uk/media/imperial-college/administration-and-support-services/registry/academic-governance/public/regulations/2021-22/Single_Set_Taught_Academic_Regulations_2021_22.pdf"
r["teaching_language"]=["English"];r["language_profile"].update({"teaching_language":["English"],"english_required":True,"language_risk":"low","verification_notes":bi("Imperial's taught regulations state that, except for specified modules, instruction is in English. The course page requires the standard English admission level and does not identify a non-English module.","Imperial'in taught yonetmeligi, belirtilmis moduller disinda egitimin Ingilizce oldugunu soyler. Ders sayfasi standart Ingilizce kabul seviyesini ister ve Ingilizce disi modul belirtmez.")})
r["application_timeline_profile"].update({"academic_year":"2026 entry (closed when checked)","intake_terms":["September 2026"],"application_deadline":"2026 entry closed (live course page does not display an exact closing date)","non_eu_deadline":"2026 entry closed (live course page does not display an exact closing date)","timeline_risk":"high","deadline_notes":bi("The live course page states that 2026 entry is closed. It does not show a calendar-day deadline, so the card preserves this limit and does not invent a 2027 date.","Canli ders sayfasi 2026 girisinin kapali oldugunu belirtir. Takvim gunu son tarihi gostermez; kart bu siniri korur ve 2027 tarihi uydurmaz.")})
r["living_profile"].update({"monthly_living_cost_gbp_per_month_min":1264,"monthly_living_cost_gbp_per_month_max":2118,"average_room_rent_gbp_per_month_min":1084,"average_room_rent_gbp_per_month_max":1114,"living_risk":"high","housing_difficulty":"high","housing_notes":bi("Imperial's 2026 London guide gives a GBP 1,264 lower to GBP 2,118 upper monthly student-spending range. Its practical planning table gives GBP 1,084/month College-run accommodation or GBP 1,114 private sector; tuition and study materials are excluded.","Imperial'in 2026 Londra rehberi aylik 1.264 GBP alt ve 2.118 GBP ust ogrenci harcama araligi verir. Pratik planlama tablosu College-run konut icin 1.084 GBP/ay, ozel sektor icin 1.114 GBP/ay verir; ogrenim ucreti ve ders malzemeleri harictir.")})
s=r.setdefault("source_profile",{});s["source_log"]=[x for x in s.get("source_log",[]) if not(isinstance(x,dict) and x.get("url") in {course,living,language})];s["source_log"] += [source(course,"Imperial Advanced Aeronautical Engineering MSc","official_program_page",["program","deadline"],"Live course page says 2026 entry is closed without a calendar-day deadline.","Canli ders sayfasi takvim gunu olmadan 2026 girisinin kapali oldugunu soyler."),source(course,"Imperial Advanced Aeronautical Engineering admission","official_admission_page",["admission","non_eu_eligibility"],"Official course page gives academic requirements, English requirement and overseas-candidate ATAS information.","Resmi ders sayfasi akademik kosullari, Ingilizce kosulunu ve yurtdisi aday ATAS bilgisini verir."),source(course,"Imperial Advanced Aeronautical Engineering fees","official_tuition_page",["tuition"],"Official course page publishes 2026 home and overseas fees.","Resmi ders sayfasi 2026 ev ve yurtdisi ucretlerini yayimlar."),source(course,"Imperial Advanced Aeronautical Engineering funding","official_scholarship_page",["scholarship","funding"],"Official course page names the Department of Aeronautics MSc Scholarship route.","Resmi ders sayfasi Department of Aeronautics MSc Scholarship yolunu adlandirir."),source(course,"Imperial Advanced Aeronautical Engineering structure","official_curriculum_page",["curriculum"],"Official course page describes course structure and individual research project.","Resmi ders sayfasi ders yapisini ve bireysel arastirma projesini aciklar."),source(living,"Imperial London living costs 2026","official_cost_of_living_page",["housing","living"],"Official page provides 2026 monthly planning ranges and accommodation components.","Resmi sayfa 2026 aylik planlama araliklari ve konaklama bilesenleri verir."),source(language,"Imperial taught academic regulations","official_university_policy_page",["language"],"Official regulations establish English as instruction language except specified modules.","Resmi yonetmelik, belirtilmis moduller disinda egitim dilini Ingilizce yapar.")];s.update({"official_program_page":course,"official_admission_page":course,"official_tuition_page":course,"official_scholarship_page":course,"official_curriculum_page":course,"official_cost_of_living_page":living,"official_language_policy_page":language,"last_verified":CHECKED});s.setdefault("field_confidence",{}).update({"language":"medium","application_timeline_profile":"medium","living_profile":"high","housing":"high"})
nl="\r\n" if "\r\n" in raw else "\n";p.write_text(json.dumps(d,ensure_ascii=False,indent=2).replace("\n",nl)+nl,encoding="utf8");print("Updated Imperial Advanced Aeronautical Engineering.")
