"""Finish two records where official sources now expose every decision field."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[1]; CHECKED="2026-07-15"
def bi(en:str,tr:str)->dict[str,str]: return {"en":en,"tr":tr}
def src(u:str,t:str,k:str,f:list[str],en:str,tr:str,c:str="high")->dict[str,Any]: return {"url":u,"title":t,"source_type":k,"access_status":"ok","last_checked":CHECKED,"relevant_fields":f,"confidence":c,"notes":bi(en,tr)}
def load(n:str):
 p=ROOT/"data_base"/n; raw=p.read_text(encoding="utf8"); return p,raw,json.loads(raw)
def rows(d): return d if isinstance(d,list) else d.get("programs",d.get("universities",[]))
def get(d,i): return next(x for x in rows(d) if x.get("id")==i)
def save(p,raw,d):
 nl="\r\n" if "\r\n" in raw else "\n";p.write_text(json.dumps(d,ensure_ascii=False,indent=2).replace("\n",nl)+nl,encoding="utf8")
def add(p,x): p["source_log"]=[q for q in p.get("source_log",[]) if not(isinstance(q,dict) and q.get("url")==x["url"] and q.get("source_type")==x["source_type"])]+[x]

def eth():
 p,raw,d=load("isvicre.json");r=get(d,"ch-eth-zurich-mech-msc")
 fee="https://ethz.ch/content/dam/ethz/main/education/finanzielles/files-en/tuition-fees.pdf"; esop="https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html"; living="https://ethz.ch/content/dam/ethz/main/education/finanzielles/files-de/lebenshaltung.pdf"; curr="https://master-mechanical-engineering.ethz.ch/curriculum.html"
 r["cost_profile"].update({"tuition_chf_per_semester":2190,"tuition_chf_per_year_min":4380,"tuition_chf_per_year_max":4380,"tuition_basis":"ETH fee group 2 published semester fee; fee group must be confirmed","verification_notes":bi("ETH's published higher fee for fee group 2 is CHF 2,190 per semester. Eligibility is based on ETH fee-group rules, not nationality alone, so this card does not assume every non-EU applicant has this status.","ETH'nin fee group 2 icin yayimladigi yuksek ucret donem basina 2.190 CHF'dir. Uygunluk sadece uyruga degil ETH fee-group kurallarina baglidir; kart her AB disi aday icin bunu varsaymaz."),"living_cost_chf_per_year":25200})
 r["scholarship_profile"].update({"available_types":["ETH Excellence Scholarship & Opportunity Programme (ESOP)"],"regional_scholarship_available":True,"regional_scholarship_name":"ESOP","non_eu_eligible":True,"scholarship_deadline":"2026-11-30 11:59 CET (HS27 ESOP/international application window)","scholarship_application_url":esop,"funding_amount_chf_per_semester":12000,"tuition_waivers":["ESOP tuition-fee waiver"],"funding_notes":bi("ESOP for the 2027/28 Master start is open 1-30 November 2026. It provides CHF 12,000 per semester plus a tuition-fee waiver for the regular Master duration; applicants need top-10% Bachelor performance and apply with the Master application.","2027/28 Master baslangici icin ESOP 1-30 Kasim 2026'da aciktir. Normal Master suresi icin donem basina 12.000 CHF ve ogrenim ucreti muafiyeti sunar; adaylarin lisans derecesinde ilk %10'da olmasi ve Master basvurusuyla basvurmasi gerekir.")})
 r["living_profile"].update({"housing_budget_chf_per_year":11300,"official_student_total_budget_chf_per_year":25200,"living_risk":"high","housing_difficulty":"high","housing_notes":bi("ETH Financial Aid's 2025 Canton Zurich planning table gives CHF 11,300/year average room rent and CHF 25,200/year individual living costs for fee groups 1 and 2. It is a current planning budget, not a room offer.","ETH Financial Aid'in 2025 Kanton Zurich planlama tablosu, fee group 1 ve 2 icin yillik ortalama oda kirasi 11.300 CHF ve bireysel yasam gideri 25.200 CHF verir. Bu oda teklifi degil guncel planlama butcesidir.")})
 r["curriculum_profile"].update({"structure":bi("Tutor-driven individual Learning Agreement across six categories.","Alti kategoriye yayilan, tutor yonlendirmeli bireysel Learning Agreement."),"core_courses":["36 ECTS Core Courses (tutor-defined)","6 ECTS Multidisciplinary Courses","2 ECTS Science in Perspective","8 ECTS Semester Project","8 ECTS Industrial Internship (12 weeks)","30 ECTS Master's Thesis (max. six months full-time)"],"mandatory_courses":["Semester Project","Industrial Internship","Master's Thesis"],"thesis_type":"30 ECTS independent research thesis (maximum six months full-time)","mandatory_internship":True,"curriculum_url":curr,"verification_notes":bi("ETH explicitly describes the six-category 90-ECTS structure. Tutor-defined core choices mean the card does not invent a fixed specialisation track.","ETH alti kategorili 90 AKTS yapisini acikca tanimlar. Core dersler tutor tarafindan belirlendigi icin kart sabit uzmanlasma hatti uydurmaz.")})
 s=r.setdefault("source_profile",{});add(s,src(fee,"ETH tuition fee groups","official_tuition_page",["tuition"],"Official ETH table gives the fee-group rate; group classification is conditional.","Resmi ETH tablosu fee-group ucretini verir; grup siniflandirmasi kosulludur."));add(s,src(esop,"ETH Excellence Scholarship & Opportunity Programme","official_scholarship_page",["scholarship","funding","deadline"],"Official page gives current HS27 dates, amount, waiver and selection conditions.","Resmi sayfa guncel HS27 tarihini, tutari, muafiyeti ve secim kosullarini verir."));add(s,src(living,"ETH Financial Aid cost of living 2025","official_cost_of_living_page",["housing","living"],"Official Canton Zurich budget gives annual room-rent and individual-living-cost figures.","Resmi Kanton Zurich butcesi yillik oda kirasi ve bireysel yasam maliyeti verir."));add(s,src(curr,"ETH MSc Mechanical Engineering curriculum","official_curriculum_page",["curriculum"],"Official curriculum gives categories, ECTS, internship and thesis structure.","Resmi mufredat kategorileri, AKTS'leri, staj ve tez yapisini verir."));s.update({"official_tuition_page":fee,"official_scholarship_page":esop,"official_cost_of_living_page":living,"official_curriculum_page":curr,"last_verified":CHECKED});s.setdefault("field_confidence",{}).update({"tuition":"medium","scholarship":"high","living_profile":"high","housing":"high","curriculum":"high"});save(p,raw,d)

def cranfield():
 p,raw,d=load("ingiltere.json");r=get(d,"cranfield-university")
 language="https://www.cranfield.ac.uk/-/media/files/short_courses_files/short-course-terms-and-conditions.ashx?hash=FA4CD369C6C35CDF62BFE532B3B3132A1D8F6952&la=en"; living="https://www.cranfield.ac.uk/study/life-on-campus/managing-money"
 r["teaching_language"]=["English"];r["language_profile"].update({"teaching_language":["English"],"english_required":True,"english_level_required":"IELTS Academic 6.5 overall, minimum 5.5 in each component","language_risk":"low","verification_notes":bi("Cranfield's official terms say courses are taught in English unless stated otherwise; the Aerospace Vehicle Design page publishes its course-specific English-test thresholds.","Cranfield'in resmi kosullari, aksi belirtilmedikce derslerin Ingilizce oldugunu soyler; Aerospace Vehicle Design sayfasi programa ozgu Ingilizce sinav esiklerini yayimlar.")})
 r["living_profile"].update({"monthly_living_cost_gbp_per_month_min":1259,"monthly_living_cost_gbp_per_month_max":2285,"average_room_rent_gbp_per_month_min":620,"average_room_rent_gbp_per_month_max":1400,"living_risk":"medium","housing_difficulty":"medium","housing_notes":bi("Cranfield's single-student guide lists monthly accommodation GBP 620-1,400, food GBP 300-400, travel GBP 39-85 and general expenses GBP 300-400. The summed guide range is GBP 1,259-2,285; it excludes childcare and varies with lifestyle.","Cranfield'in tek ogrenci rehberi aylik konaklama 620-1.400 GBP, yemek 300-400 GBP, ulasim 39-85 GBP ve genel gider 300-400 GBP listeler. Toplanan rehber araligi 1.259-2.285 GBP'dir; cocuk bakimini kapsamaz ve yasam tarzina gore degisir.")})
 s=r.setdefault("source_profile",{});add(s,src(language,"Cranfield course terms: language of instruction","official_university_policy_page",["language"],"Official terms state courses are taught in English unless otherwise specified.","Resmi kosullar, aksi belirtilmedikce derslerin Ingilizce oldugunu belirtir.","medium"));add(s,src(living,"Cranfield managing money: single-student costs","official_cost_of_living_page",["housing","living"],"Official guide lists monthly accommodation and other single-student planning components.","Resmi rehber aylik konaklama ve diger tek ogrenci planlama bilesenlerini listeler."));s.update({"official_language_policy_page":language,"official_cost_of_living_page":living,"last_verified":CHECKED});s.setdefault("field_confidence",{}).update({"language":"medium","living_profile":"high","housing":"high"});save(p,raw,d)
eth();cranfield();print("Updated ETH Mechanical Engineering and Cranfield Aerospace Vehicle Design.")
